server:
  port: 8888

spring:
  profiles:
    active: native
  security:
    user:
      name: col
      password: collm
  application:
    name: col-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties/
        git:
          uri: https://github.com/IvanLiu1102/col_config
          searchPaths: ${spring.application.name}

eureka:
  client:
    serviceUrl:
      defaultZone: http://col:collm@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: col-config-server