server:
  port: 8080
spring:
  security:
    user:
      name: col
      password: collm
  application:
    name: col-config-server
  cloud:
      config:
        server:
          git:
            uri: https://git.coding.net/yirenyishi/springcloud-config-profile
            searchPaths: 'sc-config-server'
eureka:
  client:
    serviceUrl:
      defaultZone: http://col:collm@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: col-config-server
