eureka:
  client:
    service-url:
      defaultZone: http://col:collm@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: col-zuul

server:
  port: 8400
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  profiles:
    active: csdn
  application:
    name: col-zuul
zuul:
  routes:
    col-consumer: /consumer/**
    col-provider: /provider/**
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000