spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.110.129:9092,192.168.110.131:9092,192.168.110.132:9092
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/col?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root123
    initial-size: 10
    minIdle: 5
    maxActive: 100
    maxWait: 600
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  redis:
      host: 192.168.182.128
      port: 6379
      password: col
      timeout: 1000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

server:
  port: 8089

mybatis:
  type-aliases-package: com.col.module
  mapper-locations: classpath:**/mapper/*.xml
