server:
  port: 8500

eureka:
  client:
    service-url:
      defaultZone: http://col:collm@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: col-consumer
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: col-consumer
management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  metrics:
    enabled: true

#设置feign请求响应超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000