server:
  port: 9411

spring:
  application:
    name: col-zipkin

eureka:
  client:
    service-url:
      defaultZone: http://col:collm@localhost:8761/eureka/
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      appname: col-zipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false
