server:
  port: 8090
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.132.129:9092,192.168.132.130:9092,192.168.132.131:9092
      enable-auto-commit: true
      group-id: applog
      auto-offset-reset: latest
