server:
  port: 8091
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.182.128:9092,192.168.182.129:9092,192.168.182.130:9092
      enable-auto-commit: true
      group-id: applog
      auto-offset-reset: latest
