server:
  port: 8091
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.110.129:9092,192.168.110.131:9092,192.168.110.132:9092
      enable-auto-commit: true
      group-id: applog
      auto-offset-reset: latest
